### ISSUE TITLE
Drug Addict Villager doesn't refill his trades

### ISSUE THREAD

**Issue by etil2jz** [Sollace/Psychedelicraft#10]
I cured this drug addict NPC and started to trade with him. I noticed that it doesn't refill his trades, even after leveling. There seems to be no POI block for it in the source code. So I waited the next day and still no refill.
![](https://cdn.discordapp.com/attachments/867077770386472980/1126111529750777896/2023-07-05_13.17.57.png)

**Comment by Sollace** [comment]
Eeyup. That's a major minor oversight. 

The drug addict villager is in general a bit half-baked, no pun intended.
