### ISSUE TITLE
Crash with Create 1.19.2

### ISSUE THREAD

**Issue by khronost** [Sollace/Psychedelicraft#16]
Crashed on launch with just the latest Create version, the latest Psychedelicraft, and Sodium. Crash does not happen without Create. 

Crash log: https://pastebin.com/zBQkxzKQ

Also thanks for updating the mod, I loved using it back in the day and I'm happy to see it and hopefully put it in my modern modpack.

**Comment by Sollace** [comment]
Looks like a problem with mods that add shaders. I'll have it fixed in the next update. 🙂

**Comment by Sollace** [comment]
Whoops! Forgot to close this.

It was fixed in the last release.
