### ISSUE TITLE
Rain effect ALWAYS on in the end

### ISSUE THREAD

**Issue by SkippyTrx** [Sollace/Psychedelicraft#19]
![image](https://github.com/Sollace/Psychedelicraft/assets/77331532/b5ffed77-1e95-4950-9413-5915405066c2)

Rain effect never goes away in the end, as if it was always raining. Doing "/weather clear" doesn't have an effect.

**Comment by Sollace** [comment]
I can't reproduce this. Do you have any other mods that might be causing this?

![image](https://github.com/Sollace/Psychedelicraft/assets/6429283/3b997952-9be4-4c27-ab51-28138eb9ae4e)

**Comment by SkippyTrx** [comment]
Yes I'm using bettermc mod pack with this mod slapped on top. It's the latest 1.19.2 version

**Comment by Sollace** [comment]
Cannot reproduce this in 1.19.2 either. Please remove your other mods and test again. If it's one of your other mods causing this you should report it to them.
