### ISSUE TITLE
Option to disable Molotov cocktails

### ISSUE THREAD

**Issue by ebullienc3** [Sollace/Psychedelicraft#20]
Hello there. Could you include an option for disabling molotov cocktails? And please, update the source code for 1.20.1 :)

**Comment by DINEVV** [comment]
I have the same problem with the molotov if they can really stop and updated to 1.20.1

**Comment by counter080** [comment]
Hello. I need the source code for 1.20.1 just. I can edit it myself to disable molotov`s

**Comment by Sollace** [comment]
It doesn't neeed to be updated for 1.20.1. The same build will work just fine.

**Comment by Sollace** [comment]
And in fact the current branch is already targetting 1.20.1
