### ISSUE TITLE
Everything turns into obsidian dust when you try to craft something

### ISSUE THREAD

**Issue by Blayung** [Sollace/Psychedelicraft#22]
No matter what you put in the crafting table, you always get obsidian dust for some reason.

**Comment by Blayung** [comment]
I think, that the bug is in `ivorius.psychedelicraft.recipe.FluidAwareShapelessRecipe.matches`. Making it always return false fixes the issue.

**Comment by Sollace** [comment]
There is probably some issue with how the recipes were converted to use Codecs for 1.20.2. I'm aware of the issue and will look into it soon as I get a chance to.

**Comment by Blayung** [comment]
I've seen you did [this](https://github.com/Sollace/Psychedelicraft/commit/14594996f388cc757654f0fa3b2611b776e95432), should this issue be closed?

**Comment by Sollace** [comment]
Eeyup, sorry!
