### ISSUE TITLE
Not all items are visible in the creative menu

### ISSUE THREAD

**Issue by Blayung** [Sollace/Psychedelicraft#24]
For example, the jolly ranchers are missing.

**Comment by Sollace** [comment]
Certain items aren't in the creative menu on purpose because they're not finished, or are easter egg items, like the Jolly Ranchers.

**Comment by Blayung** [comment]
Ah, okay.

**Comment by Sollace** [comment]
In case you're curious, the Jolly Ranchers are a reference to the review of the mod Yogscast did way back in the day.

**Comment by Blayung** [comment]
I thought that it had something to do with an upcoming lean implementation or sth like that.
