### ISSUE TITLE
 You cannot make all the items in survival

### ISSUE THREAD

**Issue by SmoyBTW** [Sollace/Psychedelicraft#29]
Hi !

I encountered a problem. In survival, you can actually collect seeds from each item but after that, nothing, I can't make anything from the seeds (like wine and coffee). Even with just enough item, it doesn't show me any possible recipes which is very annoying because I can only get the items in creative mode.

Version use : psychedelicraft-1.6.7+1.20.jar

Thanks for your futur answer !

Smoy

**Comment by Syddd04** [comment]
This mod doesn't support REI or JEI. It does support EMI.
