### ISSUE TITLE
Duplication glitch in some version of the mod with the tub

### ISSUE THREAD

**Issue by haloenjoyer69420** [Sollace/Psychedelicraft#30]
https://cdn.discordapp.com/attachments/1113859520947572757/1134650136476258395/0000-1236.mp4?ex=65bd8ec9&is=65ab19c9&hm=84a50ac106de011e9b3296884f84d0eb8b54490d6516599a4d00ef7fac8ad9bc&

**Comment by Sollace** [comment]
Duplicate of #28
