### ISSUE TITLE
Broken wooden vat collisions

### ISSUE THREAD

**Issue by Blayung** [Sollace/Psychedelicraft#37]
https://www.youtube.com/watch?v=aZuhVz0X30k

**Comment by Sollace** [comment]
This looks similar to an issue the vanilla game had with anvils where the hitbox is determined by what you're looking at. I'm not sure if this is something I'm even able to fix but I'll at least try to see if can replicate it.

**Comment by Sollace** [comment]
Cannot reproduce in 1.21
