### ISSUE TITLE
Another Incompatibility That's Needed To Be Fixed 

### ISSUE THREAD

**Issue by SirDingleFarts** [Sollace/Psychedelicraft#39]
My friends and I have created and been using a modpack that contains two mods, the **Essential Mod** and the **Psychedelicraft Mod.** We have been using this mod pack for couple month without an complications, but out of the blue, both mods don't work with each other anymore. Ever since Essential had received an update, that happened about three days ago, Minecraft would start to bug out or you wouldn't be able to see the Essential mod working, like starting a server in singleplayer and etc. Our modpack was **Minecraft 1.20.4** and was **Fabric 0.15.7**. We uninstalled and reinstalled both mods, but nothing worked. We even created new modpacks to see if it was the launcher that we were using. We don't know what else to do and we are hopefully waiting to see if this issue can be resolved soon.

**Comment by MimzyFang** [comment]
First of all try updating to fabric 0.15.11
And secondly please provide a log

Also since Essentials is proprietary it makes fixing the issue more complicated so please stay patient

**Comment by Sollace** [comment]
I can't do anything without a log or crash report
