### ISSUE TITLE
[Suggestion] Replace all LSD with LSA

### ISSUE THREAD

**Issue by Blayung** [Sollace/Psychedelicraft#42]
[Ivorius's said](https://github.com/Sollace/Psychedelicraft/issues/5#issuecomment-1427590637) that he didn't want to add any drugs with complicated chemical synthesis. I think he was right? And like, LSD comes from this weird wheat fungi I think, but it requires heavy chemical processing. Extracting LSA from morning glories or hawaiian baby woodrose seeds is a process that fits minecraft way better. I've seen that there already is an item named LSA Square in the creative menu (and I think you mentioned being able to craft it), but villagers still sell LSD. And you didn't remove LSD from the creative menu. So, my suggestion is to remove it maybe :D

**Comment by Sollace** [comment]
I don't plan on doing this.

1. Most crafting methods already do give you LSE
2. The only way to get LSD is by trading with a villager and the crafting method is only going to come after the 1.21 update
