### ISSUE TITLE
EMI Critical Error

### ISSUE THREAD

**Issue by trapnyu** [Sollace/Psychedelicraft#44]
https://paste.ee/p/VjLe4

The mod runs with my modpack (BigChadGuysPlus on Fabric 1.20.1) however it seems to crash EMI upon opening the inventory to check the menu.
![2024-08-12_13 37 35](https://github.com/user-attachments/assets/de7eabc5-e816-4268-ac51-3a955b87e036)
Logs linked above! :)

**Comment by Sollace** [comment]
You may need to downgrade EMI. Psychedelicraft was built to work against a specific version and loading newer ones can have this problem.

It will be fixed in 1.21 with the move to TLA
