### ISSUE TITLE
Drug effects given to all players

### ISSUE THREAD

**Issue by ghost** [Sollace/Psychedelicraft#49]
I have Psychedelicraft 1.8.0 Beta 4 for 1.21.1 on a Minecraft server, but whenever someone uses something that has visual effects, it is applied to everyone. If I do `/drug username set all 0`, it also removes everyone's effects. It seems like the effects are applied to everyone on the server rather than one person.

**Comment by ghost** [comment]
For example, if someone else on the server eats red magic mushrooms, the drug effects of red magic mushrooms are given to everyone. Even though someone else ate them, if I do `/drug @s get`, it shows red magic mushrooms.

**Comment by Sollace** [comment]
Fixed in #60
