### ISSUE TITLE
LSD crafting recipe broken

### ISSUE THREAD

**Issue by ben9292** [Sollace/Psychedelicraft#50]
Can craft LSA squares from Morning glory extract but script doesn't discern between distillation levels so any varient of morning glory extract fluid works for the recipe rather than just the specific distillation level. guessing this is an issue with lsa_square.json in the recipes folder. please help

**Comment by GitHubMcGee-TheThird** [comment]
I don't think Morning glory contains LSD only LSA so it wouldn't make sense to make LSD from it but I might be wrong

**Comment by Blayung** [comment]
@GitHubMcGee-TheThird You're right.

**Comment by ben9292** [comment]
> I don't think Morning glory contains LSD only LSA so it wouldn't make sense to make LSD from it but I might be wrong

You're correct but ingame that's how the recipe is setup. Irl you'd cleave lsa to lysergic acid and then do a peptide coupling reaction w PyBOP to produce lsd

**Comment by Sollace** [comment]
Fixed
