### ISSUE TITLE
Drink recepiticles not filling from vat BETA 4 on MC ver 1.21.1 survival

### ISSUE THREAD

**Issue by GitHubMcGee-TheThird** [Sollace/Psychedelicraft#54]
![image](https://github.com/user-attachments/assets/a9f5bbf9-e7e0-4a22-b334-37f24756f9d4)
these bottles won't fill
edit: other things (cups, mugs, flasks and shot glasses) won't fill

**Comment by rowanispoof111** [comment]
big issue

**Comment by Sollace** [comment]
Fixed. (was a problem with the item components)
