### ISSUE TITLE
cant craft obsidian bottle

### ISSUE THREAD

**Issue by patritha** [Sollace/Psychedelicraft#56]
as the title states, there is no way to craft an obsidian bottle because the recipe calls for an empty psychedelicraft glass bottle, wich is uncraftable.

screenshot:
![image](https://github.com/user-attachments/assets/639da708-66dc-4a3a-ab5c-898a1ceb1eb4)

**Comment by GitHubMcGee-TheThird** [comment]
I think it needs the bottle to be filled with water or lava (I'm not sure which or if it matters which)

**Comment by GitHubMcGee-TheThird** [comment]
But it seems the EMI crafting guide isn't fully complete

**Comment by patritha** [comment]
didnt work
![image](https://github.com/user-attachments/assets/b0c0a477-cf86-42a9-9c12-0fe305c2b581)
btw do you know how to get morning glory concentrate?

**Comment by Sollace** [comment]
Put lava in a vat, then extract the lava to a bottle. use that for crafting.

![image](https://github.com/user-attachments/assets/436765d5-8e79-4a34-b2d5-6baab3ebef50)

**Comment by patritha** [comment]
can you tell me how to get morning glory concentrate? i cant figure it out
