### ISSUE TITLE
Bugs I found

### ISSUE THREAD

**Issue by ghost** [Sollace/Psychedelicraft#8]
**Needs fixing**

- missing texture in the Hanging sign interface
![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/2946c25f-03d4-4a5c-8e04-b2dcb52ef96b)

- after drying anything on any of the two drying tables, the original item stays stuck on the table until the table is opened
![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/8b7f1a50-78d6-45e0-9741-8152445d7aaa)

- /drug command should not be accessible to all players, give it the same permission group as OP3 commands
- having a config to customize crop growth time would be nice
- **any 3-block tall crop (cannabis, hops, coca...) failed to grow to full and I was unable to bonemeal it**, this results in not being able to gather cannabis buds
- peyote doesn't grow at all, but bonemeal works fine
- **ingredients do not get removed out of your hand when putting them in the wooden vat(mash_tub)**, so there's no need to farm anything, you just need one of each (same for putting wine grapes in lattice)
- duplicating certain containers inside the vat or distillery interface while using shift and clicking the item (also the shift click is wanky, please look into it) [spam clicking the container crashes the game]
- _I believe that lsd/lsa is being worked on and I cannot wait to be able to make it, same goes for the use of tray and burner... and btw, how the f*ck do you make coffee? :D_

Thanks a lot for reviving my most favorite mod there is <3 You're doing a great work and I cannot wait for future updates.

**Comment by etil2jz** [comment]
I dont have this drying table bug, there must be something on your side

LSA can be done by finding Morning Glory flowers, put them in your crafting table to get seeds. Then take a cup or anything else, a water bucket and paper. To get the extraction, put 3 seeds on first row, the container (a cup for example) on [2][2] and the water bucket on [3][2]. Then all you have to do is put some paper next to your obtained extraction and you'll get LSA tabs :D

**Comment by Sollace** [comment]
> I dont have this drying table bug, there must be something on your side
> 
> LSA can be done by finding Morning Glory flowers, put them in your crafting table to get seeds. Then take a cup or anything else, a water bucket and paper. To get the extraction, put 3 seeds on first row, the container (a cup for example) on [2][2] and the water bucket on [3][2]. Then all you have to do is put some paper next to your obtained extraction and you'll get LSA tabs :D


Almost perfect, but you forgot that you also have to distil it a few times to get the concentrated form.

**Comment by Sollace** [comment]
I believe everything mentioned in this issue has been fixed now, except for this one:

> duplicating certain containers inside the vat or distillery interface while using shift and clicking the item (also the shift click is wanky, please look into it) [spam clicking the container crashes the game]

Can you describe in more detail what is happening here?

**Comment by ghost** [comment]
Let me try to describe it...

**Conditions for the bug to appear:**

- vat/distillery/barrel contains NO liquid
- duplication works only with EMPTY containers (buckets/mugs/cups...)

**Inside the vat/distillery/barrel interface:**
_(shift+click behaves like this... container from inventory goes to the output slot, from the output slot to the input slot, then back to inventory regardless if the bucket contains any liquid)_
_... little recommendation on how I would expect it to work_

- shift+click a full container should put it in the input slot
- shift+click an empty container should put it in the output slot
- shift+click either a full or an empty container in either slot should put it back into inventory

**bug (still inside the interface):**

- shift+click multiple containers in a stack from inventory puts all the buckets into the output slot but all except one disappear

![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/40943b61-cd2e-459e-b902-80b6be671608)
![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/52f2aa07-1c52-441d-b9d7-1126370d5532)

- shift+click container in the output slot puts it in the input slot. however, the output slot container doesn't disappear (you can infinitely dupe any container like this)

![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/809edaad-38e1-4312-b26d-512d0a988f58)
![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/8e43b34c-c654-416b-a2f6-63c702b00303)
![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/694156ed-a250-4ac9-a0f5-c52a875f1810)
![image](https://github.com/Sollace/Psychedelicraft/assets/46690658/6e2763cf-aad4-4428-a594-f11c4e52ddad)

- shift+click the output slot container quickly will crash the game with the following message (The game crashed whilst container click Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7960()" because "$$18" is null)

**Comment by ghost** [comment]
> I dont have this drying table bug, there must be something on your side
> 
> LSA can be done by finding Morning Glory flowers, put them in your crafting table to get seeds. Then take a cup or anything else, a water bucket and paper. To get the extraction, put 3 seeds on first row, the container (a cup for example) on [2][2] and the water bucket on [3][2]. Then all you have to do is put some paper next to your obtained extraction and you'll get LSA tabs :D

Thanks <3

**Comment by ghost** [comment]
Also I just realized, that a shot glass (100ml) should not be able to contain more liquid than a cup (50ml)...

**Comment by etil2jz** [comment]
> Also I just realized, that a shot glass (100ml) should not be able to contain more liquid than a cup (50ml)...

I agree, a shot glass should be something like 30ml/40ml.
___
I noticed that Syringue of Morning Glory Concentrate doesn't do any effect when used

**Comment by ghost** [comment]
> > Also I just realized, that a shot glass (100ml) should not be able to contain more liquid than a cup (50ml)...
> 
> I agree, a shot glass should be something like 30ml/40ml.
> 
> I noticed that Syringue of Morning Glory Concentrate doesn't do any effect when used

And a cup should definitely be around 250ml

**Comment by ghost** [comment]
Also I noticed, that morning glory doesn't grow vertically on the lattice...

**Comment by Sollace** [comment]
Please create separate issues for other bugs as otherwise I cannot track them.

**Comment by Sollace** [comment]
> 

Appears to be working fine when I try it. Might be it takes a while (I have gamerule randomTickSpeed 3000)
![image](https://github.com/Sollace/Psychedelicraft/assets/6429283/d7c5947e-e3a8-4a2b-a473-b4448f2964a1)

**Comment by etil2jz** [comment]
Does 894b7ff fix Cannabis buds not growing?

**Comment by Sollace** [comment]
> Does [894b7ff](https://github.com/Sollace/Psychedelicraft/commit/894b7ffa8bd5227d29d970fb2b6fcf1518a3dc45) fix Cannabis buds not growing?

No. That was fixed in https://github.com/Sollace/Psychedelicraft/commit/79e9569b0366f73f685feca3e2f0c7d04ed9056d
